%% default plot parameters
global orange
orange = [0.906 0.463 0.247];

colormap gray
CC = colormap;
CM = (CC).*repmat((1-[0.906 0.463 0.247]/0.906), size(CC,1),1);
colormap(1-CM)


fontsize = 12;
fontweight = 'normal';
fontname = 'arial';
linewidth = 2;
set(0, 'defaultfigurecolor', 'w', ...
    'defaultaxesfontsize', fontsize, ...
    'defaultaxesfontweight', fontweight, ...
    'defaultaxesfontname', fontname, ...
    'defaultaxestickdir', 'out', ...
    'defaultaxesbox', 'off', ...
    'defaultaxesydir', 'normal', ...
    'defaultlinelinewidth', linewidth, ...
    'defaultlinemarkersize', 20)
